CREATE TABLE ENTRENADOR
(
    ID_ENTRENADOR SERIAL PRIMARY KEY,
    NOMBRE        VARCHAR(30) NOT NULL,
    APELLIDOS     VARCHAR(50) NOT NULL,
    NACIONALIDAD  VARCHAR(25),
    EXPERIENCIA   INT,
    CONSTRAINT ENTRENADOR_EXPERIENCIA_CHK CHECK (EXPERIENCIA >= 0),
    CONSTRAINT PK_ENTRENADOR PRIMARY KEY (ID_ENTRENADOR)
);

CREATE TABLE JUGADORA
(
    ID_JUGADORA   SERIAL PRIMARY KEY,
    NOMBRE        VARCHAR(30) NOT NULL,
    APELLIDOS     VARCHAR(50) NOT NULL,
    POSICION      VARCHAR(20) NOT NULL,
    CONSTRAINT JUGADORA_POSICION_CHK CHECK (UPPER(POSICION) IN
                                            ('COLOCADORA', 'OPUESTO', 'CENTRAL', 'LIBERO', 'ATACANTE')),
    NACIONALIDAD  VARCHAR(25),
    EDAD          INT,
    CONSTRAINT JUGADORA_EDAD_CHK CHECK (EDAD >= 16 AND EDAD <= 50),
    DORSAL        INT         NOT NULL,
    CONSTRAINT JUGADORA_DORSAL_CHK CHECK (DORSAL >= 1 AND DORSAL <= 99),
    NOM_EQUIPO    VARCHAR(30) NOT NULL,
    ID_ENTRENADOR INT,
    CONSTRAINT JUGADORA_ENTRENADOR_FK FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR (ID_ENTRENADOR),
    CONSTRAINT PK_JUGADORA PRIMARY KEY (ID_JUGADORA)
);

CREATE TABLE PARTIDO
(
    ID_PARTIDO             SERIAL PRIMARY KEY,
    FECHA                  DATE        NOT NULL,
    EQUIPO_COMPETIDOR1     VARCHAR(50) NOT NULL,
    ENTRENADOR_COMPETIDOR1 INT,
    CONSTRAINT PARTIDO_ENTRENADOR_LOCAL_FK FOREIGN KEY (ENTRENADOR_COMPETIDOR1) REFERENCES ENTRENADOR (ID_ENTRENADOR),
    EQUIPO_COMPETIDOR2     VARCHAR(50) NOT NULL,
    ENTRENADOR_COMPETIDOR2 INT,
    CONSTRAINT PARTIDO_ENTRENADOR_VISITANTE_FK FOREIGN KEY (ENTRENADOR_COMPETIDOR2) REFERENCES ENTRENADOR (ID_ENTRENADOR),
    RESULTADO              VARCHAR(80) NOT NULL,
    DURACION               INT         NOT NULL,
    CONSTRAINT PARTIDO_DURACION_CHK CHECK (DURACION > 0),
    CONSTRAINT PK_PARTIDO PRIMARY KEY (ID_PARTIDO)
);

CREATE TABLE ESTADISTICA
(
    ID_ESTADISTICA SERIAL PRIMARY KEY,
    ID_JUGADORA    INT,
    CONSTRAINT ESTADISTICA_JUGADORA_FK FOREIGN KEY (ID_JUGADORA) REFERENCES JUGADORA (ID_JUGADORA),
    ID_PARTIDO     INT,
    CONSTRAINT ESTADISTISCA_PARTIDO_FK FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDO (ID_PARTIDO),
    ATAQUES        INT,
    CONSTRAINT ESTADISTICA_ATAQUES_CHK CHECK (ATAQUES >= 0),
    SAQUES         INT,
    CONSTRAINT ESTADISTICA_SAQUES_CHK CHECK (SAQUES >= 0),
    BLOQUEOS       INT,
    CONSTRAINT ESTADISTICA_BLOQUEOS_CHK CHECK (BLOQUEOS >= 0),
    DEFENSAS       INT,
    CONSTRAINT ESTADISTICA_DEFENSAS_CHK CHECK (DEFENSAS >= 0),
    ERRORES        INT,
    CONSTRAINT ESTADISTICA_ERRORES_CHK CHECK (ERRORES >= 0),
    CONSTRAINT PK_ESTADISTICA PRIMARY KEY (ID_ESTADISTICA)
);

CREATE TABLE USUARIO
(
    ID_USUARIO  SERIAL PRIMARY KEY,
    NOMBRE      VARCHAR(30) NOT NULL,
    APELLIDOS   VARCHAR(50) NOT NULL,
    EMAIL       VARCHAR(50),
    CONSTRAINT USUARIO_EMAIL_UNI UNIQUE (EMAIL),
    CONTRASENYA VARCHAR(20) NOT NULL,
    ID_JUGADORA INT,
    CONSTRAINT USUARIO_JUGADORA_FK FOREIGN KEY (ID_JUGADORA) REFERENCES JUGADORA (ID_JUGADORA),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE OPINION
(
    ID_OPINION  SERIAL PRIMARY KEY,
    ID_PARTIDO  INT,
    CONSTRAINT OPINION_PARTIDO_FK FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDO (ID_PARTIDO),
    ID_JUGADORA INT,
    CONSTRAINT OPINION_JUGADORA_FK FOREIGN KEY (ID_JUGADORA) REFERENCES JUGADORA (ID_JUGADORA),
    ID_USUARIO  INT,
    CONSTRAINT OPINION_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    PUNTUACION  INT,
    CONSTRAINT OPINION_PUNTUACION_CHK CHECK (PUNTUACION >= 1 AND PUNTUACION <= 10),
    COMENTARIO  VARCHAR(100),
    CONSTRAINT PK_OPINION PRIMARY KEY (ID_OPINION)
);

CREATE TABLE JUEGA
(
    ID_JUGADORA    INT,
    ID_PARTIDO     INT,
    MINUTO_ENTRADA INT,
    CONSTRAINT JUEGA_MINENTR_CHK CHECK (MINUTO_ENTRADA >= 0),
    MINUTO_SALIDA  INT,
    CONSTRAINT JUEGA_MINSAL_CHK CHECK (MINUTO_SALIDA >= 0),
    ESTADO         VARCHAR(20),
    CONSTRAINT JUEGA_ESTADO_CHK CHECK (UPPER(ESTADO) IN
                                       ('ACTIVA', 'SUSTITUIDA', 'LESIONADA', 'EXPULSADA', 'TITULAR', 'RESERVA',
                                        'INACTIVA')),
    CONSTRAINT PK_JUEGA PRIMARY KEY (ID_JUGADORA, ID_PARTIDO),
    CONSTRAINT JUEGA_JUGADORA_FK FOREIGN KEY (ID_JUGADORA) REFERENCES JUGADORA (ID_JUGADORA),
    CONSTRAINT JUEGA_PARTIDO_FK FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDO (ID_PARTIDO)
);

CREATE TABLE SIGUE
(
    ID_USUARIO             INT,
    ID_JUGADORA            INT,
    FECHA_SEGUIMIENTO      DATE,
    FRECUENCIA_INTERACCION VARCHAR(20),
    CONSTRAINT SIGUE_FRECUENCIA_CHK CHECK (FRECUENCIA_INTERACCION IN ('DIARIO', 'SEMANAL', 'MENSUAL', 'ANUAL')),
    OBSERVACIONES          VARCHAR(100),
    CONSTRAINT PK_SIGUE PRIMARY KEY (ID_USUARIO, ID_JUGADORA, FECHA_SEGUIMIENTO),
    CONSTRAINT SIGUE_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT SIGUE_JUGADORA_FK FOREIGN KEY (ID_JUGADORA) REFERENCES JUGADORA (ID_JUGADORA)
);
